import "./globals.css";
import Navbar from "./Navbar";
import { Figtree } from "next/font/google";

const figtree = Figtree({
  weight: ["400", "600", "800"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "zentur.io challenge",
  description: "Generated by Christoph Raddatz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={figtree.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
